### ISSUE TITLE
The headers object should be Dictionary<string,object> or just an object not Dictionary<string,string>

### ISSUE THREAD

**Issue by markalanevans** [sendwithus/sendwithus_csharp#15]
### Client version
Latest
### Expected behaviour
We need to set the header options transactional flag when sending an email so that you can forward it on to sparkpost. But because of the Dictionary<string,string> type, the only way to do this would be to encode the options value rather than passing you an object.

Currently i'd have to do this:

```c#
            var headerOptions = new Dictionary<string, object> { { "transactional", true } };

            email.headers.Add("options", Json.Encode(headerOptions));
```

Resulting in 
![ScreenShot of Encoding](https://www.evernote.com/l/AJE-Sm3YK51GnKVeaNQesu6v38rr3T2dA5oB/image.png)
And that encoding is probably not going to work

Instead i'd think you want us to do this

```c#
            var headerOptions = new Dictionary<string, object> { { "transactional", true } };

            email.headers.Add("options", headerOptions);
```

Resulting in something like

```
{
    "template": "tem_A5RHVP6CnRbS34UysLjYHx",
    "recipient": {
        "address": "user@email.com"
    },
    "headers": {
        "options": {
	    "transactional": true
	}
    }
}
```

And that should work fine if the headers object is a 
```c#
Dictionary<string, object>
```

**Comment by demoore** [comment]
Thanks @markalanevans for the detailed issue! This should be addressed in PR #16
