### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by sergey-netdev** [sendwithus/sendwithus_csharp#19]
### Client version

2.1.105

### Expected behaviour

SendwithusClient.dll is strong named

### Actual behaviour

SendwithusClient.dll is not strong named which blocks our solution from signing. 

Please either sign the assembly or provide 2 separate Nuget packages just like [StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis/) and [StackExchange.Redis.StrongName](https://www.nuget.org/packages/StackExchange.Redis.StrongName/).

**Comment by dylan-swu** [comment]
Hey @sergey-netdev we don't plan on providing a strong named version of this package any time soon, but you're welcome to fork and strong name. This might also work: https://github.com/dsplaisted/strongnamer for your needs.
