### ISSUE TITLE
Incompatibility to .NET Framework 4.5.1

### ISSUE THREAD

**Issue by xrnd** [sendwithus/sendwithus_csharp#2]
Development Environment: **VS 2013**
Project Type: **Class Library**
Target Framework: **.NET Framework 4.5.1**

On installing Nuget package:

> Could not install package 'SendwithusClient 1.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by demoore** [comment]
Hey @xrnd, currently this client only targets .NET Framework 4.5.2 — the readme has been updated to reflect this. We may extend support for earlier versions of .NET in the future. For now you'll need to update 4.5.2 in order to use this client.
