### ISSUE TITLE
netstandard2.0 compatible nuget

### ISSUE THREAD

**Issue by jelical** [sendwithus/sendwithus_csharp#22]
Hi. Are you planning to release metstandard2.0 compatible nuget?

**Comment by phil-swu** [comment]
Hi @jelical, you bet! I'll try and push something out today. Thanks!

**Comment by phil-swu** [comment]
Hey @jelical, 
A new release has been published! Thanks again for your patience. I'm going to close this issue, but if you have any additional questions or comments, feel free to ping us. Cheers!

**Comment by jelical** [comment]
Great! It was the last pre-release package on our build :)
